### ISSUE TITLE
NEXO NXAMP

### ISSUE THREAD

**Issue by mkurajica** [bitfocus/companion-module-nexo-nxamp#1]
Hi,

If anyone is interested in creating module for NEXO mk1/mk2 amplifiers . I have the simple poweron on/off/mute commands working trough generic TCP, got them through wireshark using NEMO app.

Port is 49280

set AMP:Power 0 0 [ 0 or 1]
0- for off
1- for on

set AMP:Overmute 0 0 [0 or 1]
0 - un-overmute all ch
1 - overmute all ch

set AMP:Ch/Mute [ch num] 0 [Mute/Unmute]
Ch num : 0,1,2,3
Mute/Unmute : 1 / 0

Nice to have the option of simple commands without full app functionality.

**Comment by mkurajica** [comment]
Module tested , everything works. thanks 👍

**Comment by daniep01** [comment]
Thanks for the update, I'll ask for the module to be included in the next release. 👍🏻

**Comment by daniep01** [comment]
This module is now available in the latest beta build at https://bitfocus.io/companion/download/builds/
